name: debian

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "dev/**"
      - "docker-compose.yml"
      - "docker-compose-dc1.yml"
      - "LICENSE"
      - "Makefile"
      - "README.md"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "dev/**"
      - "docker-compose.yml"
      - "docker-compose-dc1.yml"
      - "LICENSE"
      - "Makefile"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file dockerfiles/debian --tag samba-debian
