name: Docker Hub Access Test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull image
        run: docker pull hello-world:latest

      - name: Tag and push image
        run: |
          docker tag hello-world:latest ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:test
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:test

      - name: Remove image
        run: |
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:test
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:test