name: CI ubuntu

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dev/**'
      - 'docker-compose.yml'
      - 'docker-compose-dc1.yml'
      - 'LICENSE'
      - 'Makefile'
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'dev/**'
      - 'docker-compose.yml'
      - 'docker-compose-dc1.yml'
      - 'LICENSE'
      - 'Makefile'
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: dockerfiles/ubuntu
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: samba-ad-dc-ubuntu:latest